%% Script for Optimizing Combined Degrader model to MRM Timecourse, MRM Titration, and BRET Titration data.
%% Loading Model
clear;
close all;
clc;

addpath(genpath("Models/Combined Degrader Model"))
load("degrader_model.mat")
savename = "MG_degrader_model_fitting";


%% Initializing Experimental Data

model.experimental_data = initialize_degrader_combined_data();
% Conditions for Sperling Data.
ConditionsToOpt = 1:78;
% Setting conditions with no signal to zero
ConditionsToOpt([3 8 11 12 13 14 18 20 23 28 39 40 41 46]) = [];


% Uncomment these lines for fitting Yamanaka et al. data.
%ConditionsToOpt = 79:90;
%ConditionWeights = [10 10 10 10 10 10 1 1 1 1 1 1];


%% Estimating Parameters
% All Parameters
% ParamsToOpt = ["Pt_IKZF1_MRM","Pt_IKZF3_MRM","Pt_GSPT1_MRM","Pt_RNF166_MRM","Pt_ZFP91_MRM",...
%     "Pt_ZNF692_MRM","Pt_BRET","Pt_AS","Pt_HIBIT","Et_BRET","Et_MRM","Et_AS","Et_HIBIT","g1",...
%     "kcat_pom_IKZF1","kcat_pom_IKZF3","kcat_pom_ZFP91","kcat_pom_RNF166","kcat_pom_ZNF692","kcat_pom_SALL4","kcat_pom_PLZF",...
%     "kcat_len_IKZF1","kcat_len_IKZF3","kcat_len_ZFP91","kcat_len_RNF166","kcat_len_ZNF692","kcat_len_SALL4","kcat_len_PLZF",...
%     "kcat_ava_IKZF1","kcat_ava_IKZF3","kcat_ava_ZFP91","kcat_ava_RNF166","kcat_ava_ZNF692",...
%     "kcat_cc885_IKZF1","kcat_cc885_IKZF3","kcat_cc885_GSPT1","kcat_cc885_RNF166","kcat_cc885_ZNF692",...
%     "KD3_IKZF1","KD3_IKZF3","KD3_GSPT1", "KD3_ZFP91","KD3_RNF166","KD3_ZNF692","KD3_SALL4","KD3_PLZF",...
%     "alpha_len_IKZF1","alpha_len_IKZF3","alpha_len_GSPT1","alpha_len_ZFP91", "alpha_len_RNF166",  "alpha_len_ZNF692","alpha_len_SALL4","alpha_len_PLZF",...
%     "alpha_pom_IKZF1","alpha_pom_IKZF3","alpha_pom_GSPT1","alpha_pom_ZFP91", "alpha_pom_RNF166",  "alpha_pom_ZNF692","alpha_pom_SALL4","alpha_pom_PLZF",...
%     "alpha_ava_IKZF1","alpha_ava_IKZF3","alpha_ava_ZFP91", "alpha_ava_RNF166",  "alpha_ava_ZNF692",...
%     "alpha_cc885_IKZF1","alpha_cc885_IKZF3","alpha_cc885_GSPT1", "alpha_cc885_RNF166",  "alpha_cc885_ZNF692","dK"];

% Sperling Parameters
ParamsToOpt = ["Pt_IKZF1_MRM","Pt_IKZF3_MRM","Pt_GSPT1_MRM","Pt_RNF166_MRM","Pt_ZFP91_MRM",...
    "Pt_ZNF692_MRM","Pt_BRET","Et_BRET","Et_MRM","g1",...
    "kcat_pom_IKZF1","kcat_pom_IKZF3","kcat_pom_ZFP91","kcat_pom_RNF166","kcat_pom_ZNF692",...
    "kcat_len_IKZF1","kcat_len_IKZF3","kcat_len_ZFP91","kcat_len_RNF166","kcat_len_ZNF692",...
    "kcat_ava_IKZF1","kcat_ava_IKZF3","kcat_ava_ZFP91","kcat_ava_RNF166","kcat_ava_ZNF692",...
    "kcat_cc885_IKZF1","kcat_cc885_IKZF3","kcat_cc885_GSPT1","kcat_cc885_RNF166","kcat_cc885_ZNF692",...
    "KD3_IKZF1","KD3_IKZF3","KD3_GSPT1", "KD3_ZFP91","KD3_RNF166","KD3_ZNF692",...
    "alpha_len_IKZF1","alpha_len_IKZF3","alpha_len_GSPT1","alpha_len_ZFP91", "alpha_len_RNF166",  "alpha_len_ZNF692",...
    "alpha_pom_IKZF1","alpha_pom_IKZF3","alpha_pom_GSPT1","alpha_pom_ZFP91", "alpha_pom_RNF166",  "alpha_pom_ZNF692",...
    "alpha_ava_IKZF1","alpha_ava_IKZF3","alpha_ava_ZFP91", "alpha_ava_RNF166",  "alpha_ava_ZNF692",...
    "alpha_cc885_IKZF1","alpha_cc885_IKZF3","alpha_cc885_GSPT1", "alpha_cc885_RNF166",  "alpha_cc885_ZNF692"];

% Yamanaka parameters
% ParamsToOpt = [
%     "Pt_AS","Pt_HIBIT","Et_AS","Et_HIBIT","g1",...
%     "kcat_pom_IKZF1","kcat_pom_SALL4","kcat_pom_PLZF",...
%     "kcat_len_IKZF1","kcat_len_SALL4","kcat_len_PLZF",...
%     "KD3_IKZF1","KD3_SALL4","KD3_PLZF",...
%     "alpha_len_IKZF1","alpha_len_SALL4","alpha_len_PLZF",...
%     "alpha_pom_IKZF1","alpha_pom_SALL4","alpha_pom_PLZF","dK"];


tic
optoptions = optimoptions("particleswarm",'UseParallel',false,'MaxIterations',200*length(ParamsToOpt));
outstruct = fit_dose_response_data(model,"FitFunction",@calculate_combined_degrader_fitness, ...
    'ParamsToOpt',ParamsToOpt,...
    'savename',savename,'tspan',[0, 6],'ErrorFunction',@se,"ConditionsToOpt",ConditionsToOpt, ...
    "OptMethod",'particleswarm_ensemble',"OptOptions",optoptions,"ConditionsToOpt",...
    ConditionsToOpt,"NSets",25,"UseParallel",false,"Npools",1);
toc


