%% Script for Optimizing Combined Degrader model to MRM Timecourse, MRM Titration, and BRET Titration data.
%% Loading Model

clear;
close all;
clc;

% adding necessary folders to path
addpath(genpath("Modeling Functions"))
addpath(genpath("Models/Combined Degrader Model"))
addpath(genpath("Combined Degrader Fitting"))
load("degrader_model.mat")
savename = "sperling_data_fitting_example";

%% Initializing Experimental Data

model.experimental_data = initialize_degrader_combined_data();

% Indices for Sperling Datasets
ConditionsToOpt = 1:78;
% Indices for Yamanaka dataset
% ConditionsToOpt = 79:90;
% Adding weights when fitting Yamanaka dataset
%ConditionWeights = [100 100 100 100 100 100 1 1 1 1 1 1];

% Removing conditions with no/minimal effect or lack of paired datasets
ConditionsToOpt([3 8 11 12 13 14 18 20 23 28 39 40 41]) = [];

%% Estimating Parameters

% All Parameters
% ParamsToOpt = ["Pt_IKZF1_MRM","Pt_IKZF3_MRM","Pt_GSPT1_MRM","Pt_RNF166_MRM","Pt_ZFP91_MRM",...
%     "Pt_ZNF692_MRM","Pt_BRET","Pt_AS","Pt_HIBIT","Et_BRET","Et_MRM","Et_AS","Et_HIBIT","g1",...
%     "kcat_pom_IKZF1","kcat_pom_IKZF3","kcat_pom_ZFP91","kcat_pom_RNF166","kcat_pom_ZNF692","kcat_pom_SALL4","kcat_pom_PLZF",...
%     "kcat_len_IKZF1","kcat_len_IKZF3","kcat_len_ZFP91","kcat_len_RNF166","kcat_len_ZNF692","kcat_len_SALL4","kcat_len_PLZF",...
%     "kcat_ava_IKZF1","kcat_ava_IKZF3","kcat_ava_ZFP91","kcat_ava_RNF166","kcat_ava_ZNF692",...
%     "kcat_cc885_IKZF1","kcat_cc885_IKZF3","kcat_cc885_GSPT1","kcat_cc885_RNF166","kcat_cc885_ZNF692",...
%     "KD1_IKZF1","KD1_IKZF3","KD1_GSPT1", "KD1_ZFP91","KD1_RNF166","KD1_ZNF692","KD1_SALL4","KD1_PLZF",...
%     "alpha_len_IKZF1","alpha_len_IKZF3","alpha_len_GSPT1","alpha_len_ZFP91", "alpha_len_RNF166",  "alpha_len_ZNF692","alpha_len_SALL4","alpha_len_PLZF",...
%     "alpha_pom_IKZF1","alpha_pom_IKZF3","alpha_pom_GSPT1","alpha_pom_ZFP91", "alpha_pom_RNF166",  "alpha_pom_ZNF692","alpha_pom_SALL4","alpha_pom_PLZF",...
%     "alpha_ava_IKZF1","alpha_ava_IKZF3","alpha_ava_ZFP91", "alpha_ava_RNF166",  "alpha_ava_ZNF692",...
%     "alpha_cc885_IKZF1","alpha_cc885_IKZF3","alpha_cc885_GSPT1", "alpha_cc885_RNF166",  "alpha_cc885_ZNF692","dK"];

% Sperling Parameters
ParamsToOpt = ["Pt_IKZF1_MRM","Pt_IKZF3_MRM","Pt_GSPT1_MRM","Pt_RNF166_MRM","Pt_ZFP91_MRM",...
    "Pt_ZNF692_MRM","Pt_BRET","Et_BRET","Et_MRM","g1",...
    "kcat_pom_IKZF1","kcat_pom_IKZF3","kcat_pom_ZFP91","kcat_pom_RNF166","kcat_pom_ZNF692",...
    "kcat_len_IKZF1","kcat_len_IKZF3","kcat_len_ZFP91","kcat_len_RNF166","kcat_len_ZNF692",...
    "kcat_ava_IKZF1","kcat_ava_IKZF3","kcat_ava_ZFP91","kcat_ava_RNF166","kcat_ava_ZNF692",...
    "kcat_cc885_IKZF1","kcat_cc885_IKZF3","kcat_cc885_GSPT1","kcat_cc885_RNF166","kcat_cc885_ZNF692",...
    "KD1_IKZF1","KD1_IKZF3","KD1_GSPT1", "KD1_ZFP91","KD1_RNF166","KD1_ZNF692",...
    "alpha_len_IKZF1","alpha_len_IKZF3","alpha_len_GSPT1","alpha_len_ZFP91", "alpha_len_RNF166",  "alpha_len_ZNF692",...
    "alpha_pom_IKZF1","alpha_pom_IKZF3","alpha_pom_GSPT1","alpha_pom_ZFP91", "alpha_pom_RNF166",  "alpha_pom_ZNF692",...
    "alpha_ava_IKZF1","alpha_ava_IKZF3","alpha_ava_ZFP91", "alpha_ava_RNF166",  "alpha_ava_ZNF692",...
    "alpha_cc885_IKZF1","alpha_cc885_IKZF3","alpha_cc885_GSPT1", "alpha_cc885_RNF166",  "alpha_cc885_ZNF692"];

% Yamanaka parameters
% ParamsToOpt = [
%     "Pt_AS","Pt_HIBIT","Et_AS","Et_HIBIT","g1",...
%     "kcat_pom_IKZF1","kcat_pom_SALL4","kcat_pom_PLZF",...
%     "kcat_len_IKZF1","kcat_len_SALL4","kcat_len_PLZF",...
%     "KD1_IKZF1","KD1_SALL4","KD1_PLZF",...
%     "alpha_len_IKZF1","alpha_len_SALL4","alpha_len_PLZF",...
%     "alpha_pom_IKZF1","alpha_pom_SALL4","alpha_pom_PLZF","dK"];
tic
optoptions = optimoptions("particleswarm",'UseParallel',true,'MaxIterations',200*length(ParamsToOpt));
outstruct = fit_dose_response_data(model,"FitFunction",@calculate_combined_degrader_fitness, ...
    'ParamsToOpt',ParamsToOpt,...
    'savename',savename,'tspan',[0, 6],'ErrorFunction',@se,"ConditionsToOpt",ConditionsToOpt, ...
    "OptMethod",'particleswarm_ensemble',"OptOptions",optoptions,"ConditionsToOpt",...
    ConditionsToOpt,"NSets",25,"UseParallel",false,"Npools",1);
toc


